from db_management import create_table


S7DAVRDLR14D_schema = """
a VARCHAR NOT NULL,
b VARCHAR NOT NULL,
c VARCHAR NOT NULL,
d VARCHAR NOT NULL,
e VARCHAR NOT NULL,
f VARCHAR NOT NULL,
g VARCHAR NOT NULL,
h VARCHAR NOT NULL,
i VARCHAR NOT NULL,
j VARCHAR NOT NULL,
k VARCHAR NOT NULL,
l VARCHAR NOT NULL,
m VARCHAR NOT NULL,
n VARCHAR NOT NULL,
o VARCHAR NOT NULL,
p VARCHAR NOT NULL,
r VARCHAR NOT NULL,
t14 VARCHAR NOT NULL,
t13 VARCHAR NOT NULL,
t12 VARCHAR NOT NULL,
t11 VARCHAR NOT NULL,
t10 VARCHAR NOT NULL,
t9 VARCHAR NOT NULL,
t8 VARCHAR NOT NULL,
t7 VARCHAR NOT NULL,
t6 VARCHAR NOT NULL,
t5 VARCHAR NOT NULL,
t4 VARCHAR NOT NULL,
t3 VARCHAR NOT NULL,
t2 VARCHAR NOT NULL,
t1 VARCHAR NOT NULL,
t VARCHAR NOT NULL
"""

create_table(table="S7DAVRDLR14D", schema=S7DAVRDLR14D_schema)
