{ID1: 14Z2SFXaVkgKTW03NSyu4GWwAtCT2iuM7H8MagV_YM7w, ID1V1: 1_iDGD9XEd5Lw_AvmVo3XkAa4rBstaemnHeLKpyTgt8g,
  ID2: 16TvbvjfDAsDrT0yI9AEvByvoD6DQPHsVLSec_gsBYOI, ID2V1: 1JshfkqgC8bLhATHHkN3D5Bto19Sp3BpMBTYuAts5z_c,
  ID3: 109hg25JUZLfDN8VlHmJaUt_jQIHb3hPzfKu716dK07I, ID4: 11nw-alt5EIebGWBIQpOnsJ8HF7jEDConP9yZv3R3K-Y,
  Source1: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/Source1/',
  Source2: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/Source2/',
  T1: Voivodeships-V2, T2: Districts-V2, T3: Computable-V2, T4: DATA-V2,
  api_daily_data_Source1: 'https://api.dane.gov.pl/resources/33185,aktualne-dane-dla-wojewodztw/file',
  api_daily_data_Source2: 'https://api.dane.gov.pl/resources/33186,aktualne-dane-dla-powiatow/file',
  datetime: 2023-01-24, n: 791, sep: ;,
  save_path1: /home/blox_land/PycharmProjects/SARS-CoV-2_PL_V2/Source1/voivodeships.zip, 
  save_path2: /home/blox_land/PycharmProjects/SARS-CoV-2_PL_V2/Source2/districts.zip,
  save_path_extract1: /home/blox_land/PycharmProjects/SARS-CoV-2_PL_V2/Source1/, 
  save_path_extract2: /home/blox_land/PycharmProjects/SARS-CoV-2_PL_V2/Source2/, 
  url_source1: 'https://api.dane.gov.pl/resources/33193,archiwalne-dane-dla-wojewodztw/file',
  url_source2: 'https://api.dane.gov.pl/resources/33194,archiwalne-dane-dla-powiatow/file',
  g: '********************'
  formula1: '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/1_iDGD9XEd5Lw_AvmVo3XkAa4rBstaemnHeLKpyTgt8g"'
}
